services:
  traefik:
    image: traefik:v3.3
    networks:
      - proxy
    command: 
      --api.insecure=true
      --providers.docker
      --entryPoints.web.address=:80
      --providers.docker.exposedbydefault=false
    ports:
      - "80:80"
      - "8080:8080" # The Web UI (enabled by --api.insecure=true)
    
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  portainer:
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    ports:
      - 9443:9443
    volumes:
      - data:/data
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  data:

networks:
  proxy:
    external: true