services:
  traefik:
    image: traefik:v3.3
    networks:
      - proxy
    command: 
      --api.insecure=true
      --providers.docker
      --entryPoints.web.address=:80
      --providers.docker.exposedbydefault=false
    ports:
      - "80:80"
      - "8080:8080" # The Web UI (enabled by --api.insecure=true)
    
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  whoami:
    # A container that exposes an API to show its IP address
    image: traefik/whoami
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.docker.localhost`)"

  portainer:
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    ports:
      - 9443:9443
    volumes:
      - data:/data
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  data:

networks:
  proxy:
    external: true